### ISSUE TITLE
Platform wont Start

### ISSUE THREAD

**Issue by AmandaDLyon** [anikethsaha/Ecommerce-Full-Boilerplate-With-Admin#224]
I keep getting the following error on the Admin side

`Error: Cannot find module './utils/sessionStorage/firebaseSessionStorage'`

and the following error on the Shopper's side

`ReferenceError: firebase is not defined`

I can't get the platform started. 

Can you please help me out here? What am I missing? Is it because I haven't filled up the API keys? I dont think that would or should stop the platform from booting up.

Cheers!

**Comment by anikethsaha** [comment]
Sorry for the delayed, As mentioned in the readme, you could have mentioned me in the issue as I am not watching the repo.

did you install the dependencies ?

**Comment by AmandaDLyon** [comment]
@anikethsaha Yes I did

**Comment by anikethsaha** [comment]
can you send the screenshot of the error trace and also the repro steps

**Comment by AmandaDLyon** [comment]
Just run sudo npm run install and then npm run start and you'll see the error.

**Comment by anikethsaha** [comment]
you need to install dep from both projects

**Comment by AmandaDLyon** [comment]
Both projects being...?

**Comment by anikethsaha** [comment]
run the command from the root and then from the `Admin_Site`

**Comment by AmandaDLyon** [comment]
I'll give it a shot and let you know. Also, do you think it is possible for you to upload screenshots of your entire platform to the repo?

**Comment by AmandaDLyon** [comment]
Because the demo to the customer facing app doesnt load (the link is inactive essentially) and the admin page requires a login.

**Comment by anikethsaha** [comment]
I will try to do so .
