### ISSUE TITLE
Recomender System 

### ISSUE THREAD

**Issue by jeffin143** [anikethsaha/Ecommerce-Full-Boilerplate-With-Admin#4]
Nobody could deny the fact that ML/DL have adversely affect the online E commerce and thus it would be great to have it included in our Boiler Plate, So that after setting up, you don't have to look for someone to add it to your website. 

I guess it wouldn't be much difficult to provide a good API, We could go on with something for the admins : function like `train()` - To train it occasionally or may be keep a threshold and look for it. Always open for improvement.

**Comment by anikethsaha** [comment]
@jeffin143 Something like enabling recommendation from admin! great.
I would love it if you can collaborate for this one.

**Comment by jeffin143** [comment]
> @jeffin143 Something like enabling recommendation from admin! great.
> I would love it if you can collaborate for this one.

I would be more than happy to contribute, but bit tadd up with exams. May be could raise a PR, later this month or after that. 

Anyways I wouldn't have any problem if someone raises a PR before me for the same :) 

@anikethsaha , Always good to have a TO-DO list maintained.

**Comment by anikethsaha** [comment]
@jeffin143  Sure !
